/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jetbrains_jet_lang_resolve_objc_ObjCDescriptorResolver */

#ifndef _Included_org_jetbrains_jet_lang_resolve_objc_ObjCDescriptorResolver
#define _Included_org_jetbrains_jet_lang_resolve_objc_ObjCDescriptorResolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jetbrains_jet_lang_resolve_objc_ObjCDescriptorResolver
 * Method:    buildObjCIndex
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_jetbrains_jet_lang_resolve_objc_ObjCDescriptorResolver_buildObjCIndex
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
