// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ObjCIndex.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* ObjCClass_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ObjCClass_reflection_ = NULL;
const ::google::protobuf::Descriptor* ObjCProtocol_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ObjCProtocol_reflection_ = NULL;
const ::google::protobuf::Descriptor* TranslationUnit_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TranslationUnit_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ObjCIndex_2eproto() {
  protobuf_AddDesc_ObjCIndex_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ObjCIndex.proto");
  GOOGLE_CHECK(file != NULL);
  ObjCClass_descriptor_ = file->message_type(0);
  static const int ObjCClass_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjCClass, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjCClass, base_class_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjCClass, protocol_),
  };
  ObjCClass_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ObjCClass_descriptor_,
      ObjCClass::default_instance_,
      ObjCClass_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjCClass, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjCClass, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ObjCClass));
  ObjCProtocol_descriptor_ = file->message_type(1);
  static const int ObjCProtocol_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjCProtocol, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjCProtocol, base_protocol_),
  };
  ObjCProtocol_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ObjCProtocol_descriptor_,
      ObjCProtocol::default_instance_,
      ObjCProtocol_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjCProtocol, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjCProtocol, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ObjCProtocol));
  TranslationUnit_descriptor_ = file->message_type(2);
  static const int TranslationUnit_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TranslationUnit, class__),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TranslationUnit, protocol_),
  };
  TranslationUnit_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TranslationUnit_descriptor_,
      TranslationUnit::default_instance_,
      TranslationUnit_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TranslationUnit, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TranslationUnit, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TranslationUnit));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ObjCIndex_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ObjCClass_descriptor_, &ObjCClass::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ObjCProtocol_descriptor_, &ObjCProtocol::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TranslationUnit_descriptor_, &TranslationUnit::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ObjCIndex_2eproto() {
  delete ObjCClass::default_instance_;
  delete ObjCClass_reflection_;
  delete ObjCProtocol::default_instance_;
  delete ObjCProtocol_reflection_;
  delete TranslationUnit::default_instance_;
  delete TranslationUnit_reflection_;
}

void protobuf_AddDesc_ObjCIndex_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017ObjCIndex.proto\"\?\n\tObjCClass\022\014\n\004name\030\001"
    " \002(\t\022\022\n\nbase_class\030\002 \001(\t\022\020\n\010protocol\030\003 \003"
    "(\t\"3\n\014ObjCProtocol\022\014\n\004name\030\001 \002(\t\022\025\n\rbase"
    "_protocol\030\002 \003(\t\"M\n\017TranslationUnit\022\031\n\005cl"
    "ass\030\001 \003(\0132\n.ObjCClass\022\037\n\010protocol\030\002 \003(\0132"
    "\r.ObjCProtocol", 214);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ObjCIndex.proto", &protobuf_RegisterTypes);
  ObjCClass::default_instance_ = new ObjCClass();
  ObjCProtocol::default_instance_ = new ObjCProtocol();
  TranslationUnit::default_instance_ = new TranslationUnit();
  ObjCClass::default_instance_->InitAsDefaultInstance();
  ObjCProtocol::default_instance_->InitAsDefaultInstance();
  TranslationUnit::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ObjCIndex_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ObjCIndex_2eproto {
  StaticDescriptorInitializer_ObjCIndex_2eproto() {
    protobuf_AddDesc_ObjCIndex_2eproto();
  }
} static_descriptor_initializer_ObjCIndex_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int ObjCClass::kNameFieldNumber;
const int ObjCClass::kBaseClassFieldNumber;
const int ObjCClass::kProtocolFieldNumber;
#endif  // !_MSC_VER

ObjCClass::ObjCClass()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ObjCClass::InitAsDefaultInstance() {
}

ObjCClass::ObjCClass(const ObjCClass& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ObjCClass::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  base_class_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ObjCClass::~ObjCClass() {
  SharedDtor();
}

void ObjCClass::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (base_class_ != &::google::protobuf::internal::kEmptyString) {
    delete base_class_;
  }
  if (this != default_instance_) {
  }
}

void ObjCClass::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ObjCClass::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ObjCClass_descriptor_;
}

const ObjCClass& ObjCClass::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ObjCIndex_2eproto();  return *default_instance_;
}

ObjCClass* ObjCClass::default_instance_ = NULL;

ObjCClass* ObjCClass::New() const {
  return new ObjCClass;
}

void ObjCClass::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
    if (has_base_class()) {
      if (base_class_ != &::google::protobuf::internal::kEmptyString) {
        base_class_->clear();
      }
    }
  }
  protocol_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ObjCClass::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_base_class;
        break;
      }
      
      // optional string base_class = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_base_class:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_base_class()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->base_class().data(), this->base_class().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_protocol;
        break;
      }
      
      // repeated string protocol = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_protocol:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_protocol()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->protocol(0).data(), this->protocol(0).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_protocol;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ObjCClass::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }
  
  // optional string base_class = 2;
  if (has_base_class()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->base_class().data(), this->base_class().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->base_class(), output);
  }
  
  // repeated string protocol = 3;
  for (int i = 0; i < this->protocol_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->protocol(i).data(), this->protocol(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->protocol(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ObjCClass::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }
  
  // optional string base_class = 2;
  if (has_base_class()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->base_class().data(), this->base_class().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->base_class(), target);
  }
  
  // repeated string protocol = 3;
  for (int i = 0; i < this->protocol_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->protocol(i).data(), this->protocol(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->protocol(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ObjCClass::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }
    
    // optional string base_class = 2;
    if (has_base_class()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->base_class());
    }
    
  }
  // repeated string protocol = 3;
  total_size += 1 * this->protocol_size();
  for (int i = 0; i < this->protocol_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->protocol(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ObjCClass::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ObjCClass* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ObjCClass*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ObjCClass::MergeFrom(const ObjCClass& from) {
  GOOGLE_CHECK_NE(&from, this);
  protocol_.MergeFrom(from.protocol_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_base_class()) {
      set_base_class(from.base_class());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ObjCClass::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ObjCClass::CopyFrom(const ObjCClass& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ObjCClass::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void ObjCClass::Swap(ObjCClass* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(base_class_, other->base_class_);
    protocol_.Swap(&other->protocol_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ObjCClass::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ObjCClass_descriptor_;
  metadata.reflection = ObjCClass_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int ObjCProtocol::kNameFieldNumber;
const int ObjCProtocol::kBaseProtocolFieldNumber;
#endif  // !_MSC_VER

ObjCProtocol::ObjCProtocol()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ObjCProtocol::InitAsDefaultInstance() {
}

ObjCProtocol::ObjCProtocol(const ObjCProtocol& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ObjCProtocol::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ObjCProtocol::~ObjCProtocol() {
  SharedDtor();
}

void ObjCProtocol::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void ObjCProtocol::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ObjCProtocol::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ObjCProtocol_descriptor_;
}

const ObjCProtocol& ObjCProtocol::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ObjCIndex_2eproto();  return *default_instance_;
}

ObjCProtocol* ObjCProtocol::default_instance_ = NULL;

ObjCProtocol* ObjCProtocol::New() const {
  return new ObjCProtocol;
}

void ObjCProtocol::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
  }
  base_protocol_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ObjCProtocol::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_base_protocol;
        break;
      }
      
      // repeated string base_protocol = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_base_protocol:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_base_protocol()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->base_protocol(0).data(), this->base_protocol(0).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_base_protocol;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ObjCProtocol::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }
  
  // repeated string base_protocol = 2;
  for (int i = 0; i < this->base_protocol_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->base_protocol(i).data(), this->base_protocol(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->base_protocol(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ObjCProtocol::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }
  
  // repeated string base_protocol = 2;
  for (int i = 0; i < this->base_protocol_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->base_protocol(i).data(), this->base_protocol(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->base_protocol(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ObjCProtocol::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }
    
  }
  // repeated string base_protocol = 2;
  total_size += 1 * this->base_protocol_size();
  for (int i = 0; i < this->base_protocol_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->base_protocol(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ObjCProtocol::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ObjCProtocol* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ObjCProtocol*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ObjCProtocol::MergeFrom(const ObjCProtocol& from) {
  GOOGLE_CHECK_NE(&from, this);
  base_protocol_.MergeFrom(from.base_protocol_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ObjCProtocol::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ObjCProtocol::CopyFrom(const ObjCProtocol& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ObjCProtocol::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void ObjCProtocol::Swap(ObjCProtocol* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    base_protocol_.Swap(&other->base_protocol_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ObjCProtocol::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ObjCProtocol_descriptor_;
  metadata.reflection = ObjCProtocol_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int TranslationUnit::kClassFieldNumber;
const int TranslationUnit::kProtocolFieldNumber;
#endif  // !_MSC_VER

TranslationUnit::TranslationUnit()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void TranslationUnit::InitAsDefaultInstance() {
}

TranslationUnit::TranslationUnit(const TranslationUnit& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void TranslationUnit::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TranslationUnit::~TranslationUnit() {
  SharedDtor();
}

void TranslationUnit::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TranslationUnit::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TranslationUnit::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TranslationUnit_descriptor_;
}

const TranslationUnit& TranslationUnit::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ObjCIndex_2eproto();  return *default_instance_;
}

TranslationUnit* TranslationUnit::default_instance_ = NULL;

TranslationUnit* TranslationUnit::New() const {
  return new TranslationUnit;
}

void TranslationUnit::Clear() {
  class__.Clear();
  protocol_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TranslationUnit::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .ObjCClass class = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_class:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_class_()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_class;
        if (input->ExpectTag(18)) goto parse_protocol;
        break;
      }
      
      // repeated .ObjCProtocol protocol = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_protocol:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_protocol()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_protocol;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void TranslationUnit::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .ObjCClass class = 1;
  for (int i = 0; i < this->class__size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->class_(i), output);
  }
  
  // repeated .ObjCProtocol protocol = 2;
  for (int i = 0; i < this->protocol_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->protocol(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* TranslationUnit::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .ObjCClass class = 1;
  for (int i = 0; i < this->class__size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->class_(i), target);
  }
  
  // repeated .ObjCProtocol protocol = 2;
  for (int i = 0; i < this->protocol_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->protocol(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int TranslationUnit::ByteSize() const {
  int total_size = 0;
  
  // repeated .ObjCClass class = 1;
  total_size += 1 * this->class__size();
  for (int i = 0; i < this->class__size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->class_(i));
  }
  
  // repeated .ObjCProtocol protocol = 2;
  total_size += 1 * this->protocol_size();
  for (int i = 0; i < this->protocol_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->protocol(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TranslationUnit::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TranslationUnit* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TranslationUnit*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TranslationUnit::MergeFrom(const TranslationUnit& from) {
  GOOGLE_CHECK_NE(&from, this);
  class__.MergeFrom(from.class__);
  protocol_.MergeFrom(from.protocol_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TranslationUnit::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TranslationUnit::CopyFrom(const TranslationUnit& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TranslationUnit::IsInitialized() const {
  
  for (int i = 0; i < class__size(); i++) {
    if (!this->class_(i).IsInitialized()) return false;
  }
  for (int i = 0; i < protocol_size(); i++) {
    if (!this->protocol(i).IsInitialized()) return false;
  }
  return true;
}

void TranslationUnit::Swap(TranslationUnit* other) {
  if (other != this) {
    class__.Swap(&other->class__);
    protocol_.Swap(&other->protocol_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TranslationUnit::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TranslationUnit_descriptor_;
  metadata.reflection = TranslationUnit_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
