/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jet_runtime_objc_Native */

#ifndef _Included_jet_runtime_objc_Native
#define _Included_jet_runtime_objc_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jet_runtime_objc_Native
 * Method:    dlopen
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jet_runtime_objc_Native_dlopen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jet_runtime_objc_Native
 * Method:    objc_getClass
 * Signature: (Ljava/lang/String;)Ljet/runtime/objc/NativePointer;
 */
JNIEXPORT jobject JNICALL Java_jet_runtime_objc_Native_objc_1getClass
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jet_runtime_objc_Native
 * Method:    objc_msgSend
 * Signature: (Ljet/runtime/objc/NativePointer;Ljet/runtime/objc/NativePointer;[Ljava/lang/Object;)Ljet/runtime/objc/NativePointer;
 */
JNIEXPORT jobject JNICALL Java_jet_runtime_objc_Native_objc_1msgSend
  (JNIEnv *, jclass, jobject, jobject, jobjectArray);

/*
 * Class:     jet_runtime_objc_Native
 * Method:    sel_registerName
 * Signature: (Ljava/lang/String;)Ljet/runtime/objc/NativePointer;
 */
JNIEXPORT jobject JNICALL Java_jet_runtime_objc_Native_sel_1registerName
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
