/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jet_runtime_objc_Native */

#ifndef _Included_jet_runtime_objc_Native
#define _Included_jet_runtime_objc_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jet_runtime_objc_Native
 * Method:    dlopen
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jet_runtime_objc_Native_dlopen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jet_runtime_objc_Native
 * Method:    objc_getClass
 * Signature: (Ljava/lang/String;)Ljet/runtime/objc/ID;
 */
JNIEXPORT jobject JNICALL Java_jet_runtime_objc_Native_objc_1getClass
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jet_runtime_objc_Native
 * Method:    objc_msgSendPrimitive
 * Signature: (Ljet/runtime/objc/ID;Ljava/lang/String;[Ljet/runtime/objc/ID;)J
 */
JNIEXPORT jlong JNICALL Java_jet_runtime_objc_Native_objc_1msgSendPrimitive
  (JNIEnv *, jclass, jobject, jstring, jobjectArray);

/*
 * Class:     jet_runtime_objc_Native
 * Method:    objc_msgSendObjCObject
 * Signature: (Ljet/runtime/objc/ID;Ljava/lang/String;[Ljet/runtime/objc/ID;)Ljet/runtime/objc/ObjCObject;
 */
JNIEXPORT jobject JNICALL Java_jet_runtime_objc_Native_objc_1msgSendObjCObject
  (JNIEnv *, jclass, jobject, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
